name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create .love file
        run: |
          cd source
          zip -r ../barnyard-brawl.love .
          
      - name: Download LÖVE
        run: |
          curl -L -o love-11.5-win64.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
          curl -L -o love-11.5-macos.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-macos.zip
          
      - name: Extract LÖVE
        run: |
          unzip love-11.5-win64.zip
          unzip love-11.5-macos.zip
          
      - name: Create Windows executable
        run: |
          cat love-11.5-win64/love.exe barnyard-brawl.love > barnyard-brawl.exe
          
      - name: Create Mac executable
        run: |
          # Copy love.app and rename it
          cp -r love.app barnyard-brawl.app
          
          # Copy .love file to Resources directory
          cp barnyard-brawl.love barnyard-brawl.app/Contents/Resources/
          
          # Modify Info.plist
          sed -i 's/org.love2d.love/com.bold-it.barnyard-brawl/g' barnyard-brawl.app/Contents/Info.plist
          sed -i 's/LÖVE/Barnyard Brawl/g' barnyard-brawl.app/Contents/Info.plist
          
          # Remove UTExportedTypeDeclarations section
          sed -i '/UTExportedTypeDeclarations/,/<\/array>/d' barnyard-brawl.app/Contents/Info.plist
          
          # Create zip file with symlinks preserved
          zip -y -r barnyard-brawl-mac.zip barnyard-brawl.app
          
      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          VERSION: ${{ github.run_number }}
        run: |
          ./butler push barnyard-brawl.exe ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:windows --userversion ${{ env.VERSION }}
          ./butler push barnyard-brawl.love ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:linux --userversion ${{ env.VERSION }}
          ./butler push barnyard-brawl-mac.zip ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:mac --userversion ${{ env.VERSION }}

