name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create .love file
        run: |
          cd source
          zip -r ../barnyard-brawl.love .
          
      - name: Download LÖVE
        run: |
          wget https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
          wget https://github.com/love2d/love/releases/download/11.5/love-11.5-macos.zip
          
      - name: Extract LÖVE
        run: |
          unzip love-11.5-win64.zip
          unzip love-11.5-macos.zip
          
      - name: Create Windows executable
        run: |
          cat love-11.5-win64/love.exe barnyard-brawl.love > barnyard-brawl.exe
          
      - name: Create Mac executable
        run: |
          cat love-11.5-macos/love.app/Contents/MacOS/love barnyard-brawl.love > barnyard-brawl-mac
          chmod +x barnyard-brawl-mac
          
      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler.exe
          
      - name: Push to itch.io
        env:
          ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
          VERSION: ${{ github.run_number }}
        run: |
          ./butler.exe push barnyard-brawl.exe ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:windows --userversion ${{ env.VERSION }}
          ./butler.exe push barnyard-brawl.love ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:linux --userversion ${{ env.VERSION }}
          ./butler.exe push barnyard-brawl-mac ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:mac --userversion ${{ env.VERSION }}

